### ISSUE TITLE
support helm chart upgrades OOTB

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x-plugins/jx-updatebot#2]
with the old [jx step create pullrequest chart](https://jenkins-x.io/commands/jx_step_create_pullrequest_chart/) we baked in the knowledge of how to upgrade a helm version change in source code.

it might be nice to add helm as a change option in the `.jx/updatebot.yaml` file format so folks could upgrade helm charts without worrying about the files to match + the regex stuff.

e.g. here's the code...
https://github.com/jenkins-x/jx/blob/master/pkg/cmd/step/create/pr/step_create_pr_chart.go#L94

so we could maybe enhance the config file: https://github.com/jenkins-x/jx-cli/blob/master/.jx/updatebot.yaml

to allow

```yaml

apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/jenkins-x/jxr-versions
      changes:
        - chart: 
            name: my-chart
```
