### ISSUE TITLE
support creating PRs on all `SourceRepository` resources

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x-plugins/jx-updatebot#3]
rather than listing every git repository explicitly in the `.jx/updatebot.yaml` file it might be nice to be able to specify some kind of pattern match of all the `SourceRepository` resources for all the repos that are imported into Jenkins X.

e.g. if you have 10 repos imported into Jenkins X and you are releasing a new library/binary/thing and want to PR all your other 9 repos to upgrade to use it you might just want to specify a rule for which `SourceRepository` repos to upgrade (if they match the regex/files).

e.g. instead of...

```yaml
apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/myorg/repo1
...
        - https://github.com/myorg/repoN
      changes:
        - regex:
            pattern: "FROM\\s+image: gcr.io/myorg/something:(.*)"
            files:
              - "Dockerfile*"
```

it might be nice to have a rule to match all repos (but the current repo)...

```yaml
apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - repositories:
        includes: 
          - myorg/*
        excludes:
          - *docs  
      changes:
        - regex:
            pattern: "FROM\\s+image: gcr.io/myorg/something:(.*)"
            files:
              - "Dockerfile*"
```
by adding to the [Rule](https://github.com/jenkins-x-plugins/jx-updatebot/blob/master/pkg/apis/updatebot/v1alpha1/types.go#L31) struct something like...

```go
// Rule specifies a set of repositories and changes
type Rule struct {James Strachan, 30 days ago: • fix: initial spike
	// URLs the git URLs of the repositories to create a Pull Request on
	URLs []string `json:"urls"`

        // Repositories provides a filter of repositories to find (via the `SourceRepository` CRDs)
        Repositories *RepositoryFilter

	// Changes the changes to perform on the repositories
	Changes []Change `json:"changes"`
}
....
if rule.Repositories != nil {
	srList, err := jxClient.JenkinsV1().SourceRepositories(ns).List(context.TODO(), metav1.ListOptions{})
	if err != nil {
		return errors.Wrapf(err, "failed to find any SourceRepositories in namespace %s", ns)
	}
        // lets add the URLs of all the matching SourceRepository resources...
         for _, sr := range srList.Items {
           if rule.Repositories.Matches(&sr) {
              rule.URLs = append(rule.URLs, sr.Spec.URL)
           }
       }
}
```

then we can use include/exclude patterns on the repository owner/repo strings to find which SourceRepository's to process etc
